/**
 * Company Data - Auto-generated file
 *
 * DO NOT EDIT MANUALLY!
 * This file is generated by scripts/sync-premarket-companies.ts
 *
 * To update, run: npx tsx scripts/sync-premarket-companies.ts
 * Last synced: 2026-01-12T11:42:59.535Z
 */

/**
 * Known public companies with stock tickers
 * Format: { 'Display Name': 'slug-for-api' }
 */
export const KNOWN_COMPANIES: Record<string, string> = {
  'Accenture': 'accenture',
  'Adidas': 'adidas',
  'Adobe': 'adobe',
  'Airbnb': 'airbnb',
  'Allianz': 'allianz',
  'Alphabet': 'alphabet',
  'Amazon': 'amazon',
  'AMD': 'amd',
  'Apple': 'apple',
  'ARM': 'arm',
  'ASML': 'asml',
  'Atlassian': 'atlassian',
  'BASF': 'basf',
  'Bayer': 'bayer',
  'Block': 'block',
  'BMW': 'bmw',
  'Broadcom': 'broadcom',
  'Cloudflare': 'cloudflare',
  'Coinbase': 'coinbase',
  'CrowdStrike': 'crowdstrike',
  'Databricks': 'databricks',
  'Disney': 'disney',
  'DocuSign': 'docusign',
  'DoorDash': 'doordash',
  'Facebook': 'facebook',
  'Ford': 'ford',
  'GitHub': 'github',
  'GitLab': 'gitlab',
  'Google': 'google',
  'IBM': 'ibm',
  'Intel': 'intel',
  'JPMorgan': 'jpmorgan',
  'Lucid': 'lucid',
  'Mastercard': 'mastercard',
  'Mercedes': 'mercedes',
  'Meta': 'meta',
  'Microsoft': 'microsoft',
  'Netflix': 'netflix',
  'Nvidia': 'nvidia',
  'Oracle': 'oracle',
  'Palantir': 'palantir',
  'PayPal': 'paypal',
  'Pinterest': 'pinterest',
  'Porsche': 'porsche',
  'Qualcomm': 'qualcomm',
  'Rivian': 'rivian',
  'Robinhood': 'robinhood',
  'Roblox': 'roblox',
  'Salesforce': 'salesforce',
  'Samsung': 'samsung',
  'SAP': 'sap',
  'Schneider Electric': 'schneider-electric',
  'ServiceNow': 'servicenow',
  'Shopify': 'shopify',
  'Siemens': 'siemens',
  'Snap': 'snap',
  'Snowflake': 'snowflake',
  'SpaceX': 'spacex',
  'Spotify': 'spotify',
  'Square': 'square',
  'Stripe': 'stripe',
  'Tesla': 'tesla',
  'TSMC': 'tsmc',
  'Twilio': 'twilio',
  'Uber': 'uber',
  'Unity': 'unity',
  'Visa': 'visa',
  'Volkswagen': 'volkswagen',
  'Workday': 'workday',
  'Zalando': 'zalando',
  'Zoom': 'zoom',
}

/**
 * Known premarket companies from glitch.green API
 * Format: { 'Company Name': 'API Name' }
 * Total: 0 companies
 */
export const KNOWN_PREMARKET_COMPANIES: Record<string, string> = {

}

/**
 * Check if a company name is a known public company
 */
export function isPublicCompany(name: string): boolean {
  return name in KNOWN_COMPANIES
}

/**
 * Check if a company name is a known premarket company
 */
export function isPremarketCompany(name: string): boolean {
  return name in KNOWN_PREMARKET_COMPANIES
}

/**
 * Get the slug/API name for a company
 */
export function getCompanySlug(name: string): string | undefined {
  return KNOWN_COMPANIES[name] || KNOWN_PREMARKET_COMPANIES[name]
}

/**
 * Check if a company name is known (public or premarket)
 */
export function isKnownCompany(name: string): boolean {
  return isPublicCompany(name) || isPremarketCompany(name)
}
