/**
 * Company Data - Auto-generated file
 *
 * DO NOT EDIT MANUALLY!
 * This file is generated by scripts/sync-premarket-companies.ts
 *
 * To update, run: npx tsx scripts/sync-premarket-companies.ts
 * Last synced: 2026-01-13T10:23:04.642Z
 */

/**
 * Known public companies with stock tickers
 * Format: { 'Display Name': 'slug-for-api' }
 */
export const KNOWN_COMPANIES: Record<string, string> = {
  'Accenture': 'accenture',
  'Adidas': 'adidas',
  'Adobe': 'adobe',
  'AES': 'aes',
  'Airbnb': 'airbnb',
  'Allianz': 'allianz',
  'Alphabet': 'alphabet',
  'Amazon': 'amazon',
  'AMD': 'amd',
  'Apple': 'apple',
  'ARM': 'arm',
  'ASML': 'asml',
  'Atlassian': 'atlassian',
  'BASF': 'basf',
  'Bayer': 'bayer',
  'Block': 'block',
  'BMW': 'bmw',
  'Broadcom': 'broadcom',
  'Charter Communications': 'charter-communications',
  'Cloudflare': 'cloudflare',
  'Coinbase': 'coinbase',
  'Comcast': 'comcast',
  'CrowdStrike': 'crowdstrike',
  'Databricks': 'databricks',
  'Disney': 'disney',
  'DocuSign': 'docusign',
  'DoorDash': 'doordash',
  'Everest Group': 'everest-group',
  'Facebook': 'facebook',
  'Ford': 'ford',
  'GitHub': 'github',
  'GitLab': 'gitlab',
  'Global Payments': 'global-payments',
  'Google': 'google',
  'HP': 'hp',
  'IBM': 'ibm',
  'Intel': 'intel',
  'JPMorgan': 'jpmorgan',
  'Lucid': 'lucid',
  'Mastercard': 'mastercard',
  'Mercedes': 'mercedes',
  'Meta': 'meta',
  'Microsoft': 'microsoft',
  'Netflix': 'netflix',
  'Nvidia': 'nvidia',
  'Oracle': 'oracle',
  'Palantir': 'palantir',
  'PayPal': 'paypal',
  'Pinterest': 'pinterest',
  'Porsche': 'porsche',
  'Qualcomm': 'qualcomm',
  'Rivian': 'rivian',
  'Robinhood': 'robinhood',
  'Roblox': 'roblox',
  'Salesforce': 'salesforce',
  'Samsung': 'samsung',
  'SAP': 'sap',
  'Schneider Electric': 'schneider-electric',
  'ServiceNow': 'servicenow',
  'Shopify': 'shopify',
  'Siemens': 'siemens',
  'Snap': 'snap',
  'Snowflake': 'snowflake',
  'SpaceX': 'spacex',
  'Spotify': 'spotify',
  'Square': 'square',
  'Stripe': 'stripe',
  'Tesla': 'tesla',
  'TSMC': 'tsmc',
  'Twilio': 'twilio',
  'Uber': 'uber',
  'Unity': 'unity',
  'Viatris': 'viatris',
  'Visa': 'visa',
  'Volkswagen': 'volkswagen',
  'Workday': 'workday',
  'Zalando': 'zalando',
  'Zoom': 'zoom',
}

/**
 * Known premarket companies from glitch.green API
 * Format: { 'Company Name': 'API Name' }
 * Total: 0 companies
 */
export const KNOWN_PREMARKET_COMPANIES: Record<string, string> = {

}

/**
 * Company name aliases - maps alternative names to canonical company names
 * Format: { 'Alias': 'Canonical Name' }
 * These are NOT auto-generated and can be edited manually
 */
export const COMPANY_ALIASES: Record<string, { canonical: string; type: 'public' | 'premarket' }> = {
  'Cursor': { canonical: 'Anysphere', type: 'premarket' },
}

/**
 * Resolve an alias to its canonical company name and type
 */
export function resolveAlias(name: string): { canonical: string; type: 'public' | 'premarket' } | undefined {
  return COMPANY_ALIASES[name]
}

/**
 * Check if a company name is a known public company (including aliases)
 */
export function isPublicCompany(name: string): boolean {
  if (name in KNOWN_COMPANIES) return true
  const alias = COMPANY_ALIASES[name]
  return alias?.type === 'public'
}

/**
 * Check if a company name is a known premarket company (including aliases)
 */
export function isPremarketCompany(name: string): boolean {
  if (name in KNOWN_PREMARKET_COMPANIES) return true
  const alias = COMPANY_ALIASES[name]
  return alias?.type === 'premarket'
}

/**
 * Get the slug/API name for a company (resolves aliases)
 */
export function getCompanySlug(name: string): string | undefined {
  if (KNOWN_COMPANIES[name]) return KNOWN_COMPANIES[name]
  if (KNOWN_PREMARKET_COMPANIES[name]) return KNOWN_PREMARKET_COMPANIES[name]

  // Check aliases
  const alias = COMPANY_ALIASES[name]
  if (alias) {
    if (alias.type === 'public') return KNOWN_COMPANIES[alias.canonical]
    if (alias.type === 'premarket') return KNOWN_PREMARKET_COMPANIES[alias.canonical] || alias.canonical.toLowerCase()
  }
  return undefined
}

/**
 * Check if a company name is known (public or premarket, including aliases)
 */
export function isKnownCompany(name: string): boolean {
  return isPublicCompany(name) || isPremarketCompany(name)
}
