import { describe, it, expect } from 'vitest'
import { buildReflectionPrompt } from '@/lib/podcast/intermezzo'

// The intermezzo is generated by a separate Haiku call. Its prompt must pin the
// dialog language to the main podcast's language (ttsLang), otherwise an English
// podcast drifts into German for the reflection block (observed 2026-07-11).
describe('buildReflectionPrompt language pinning', () => {
  const trailing = 'HOST: [warm] The compute discipline is the real story.\nGUEST: [dry] With a T.'
  const leading = 'HOST: [energized] Now — China. Tencent.'

  it('pins the dialog to English for an English podcast (ttsLang=en)', () => {
    const p = buildReflectionPrompt(trailing, leading, 'en')
    expect(p).toMatch(/\bEnglish\b/)
  })

  it('pins the dialog to German for a German podcast (ttsLang=de)', () => {
    const p = buildReflectionPrompt(trailing, leading, 'de')
    expect(p).toMatch(/\bGerman\b/)
  })

  it('does not hard-code a German-only instruction/example for the English case', () => {
    const p = buildReflectionPrompt(trailing, leading, 'en')
    // The old prompt was written entirely in German and carried a German
    // few-shot example — the very thing that dragged the output into German.
    expect(p).not.toMatch(/Du schreibst einen kurzen Selbstreflexions-Dialog/)
    expect(p).not.toMatch(/Manchmal frag ich mich/)
  })

  it('still keeps speech-direction tags in English (both languages)', () => {
    for (const lang of ['de', 'en'] as const) {
      const p = buildReflectionPrompt(trailing, leading, lang)
      expect(p.toLowerCase()).toContain('bracket')
    }
  })
})
